import ReactMarkdown from 'react-markdown';
import { Copy, Check, FileText, Download } from 'lucide-react';
import { useState } from 'react';
import { motion } from 'framer-motion';

interface ReportViewProps {
  content: string;
  source?: string;
}

export function ReportView({ content, source = 'System' }: ReportViewProps) {
  const [copied, setCopied] = useState(false);

  const handleCopy = () => {
    navigator.clipboard.writeText(content);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownload = () => {
    const blob = new Blob([content], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `mission-report-${new Date().toISOString().slice(0, 10)}.md`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <motion.div
      initial={{ opacity: 0, scale: 0.95 }}
      animate={{ opacity: 1, scale: 1 }}
      transition={{ duration: 0.5, ease: 'easeOut' }}
      className="group relative flex h-full flex-col overflow-hidden rounded-xl border border-white/10 bg-[#0a0a0a]/80 shadow-2xl backdrop-blur-xl"
    >
      {/* Header */}
      <div className="flex shrink-0 items-center justify-between border-b border-white/5 bg-white/5 px-6 py-4 backdrop-blur-md">
        <div className="flex items-center gap-4">
          <div className="from-primary/20 to-secondary/20 flex h-10 w-10 items-center justify-center rounded-xl bg-gradient-to-br shadow-inner ring-1 ring-white/10">
            <FileText className="text-primary h-5 w-5" />
          </div>
          <div>
            <h3 className="text-lg font-bold tracking-tight text-white">Mission Report</h3>
            <div className="text-muted-foreground flex items-center gap-2 text-xs">
              <span className="relative flex h-2 w-2">
                <span className="absolute inline-flex h-full w-full animate-ping rounded-full bg-green-400 opacity-75"></span>
                <span className="relative inline-flex h-2 w-2 rounded-full bg-green-500"></span>
              </span>
              <span>Generated by {source}</span>
            </div>
          </div>
        </div>

        <div className="flex items-center gap-2">
          <button
            onClick={handleDownload}
            className="text-muted-foreground rounded-lg p-2 transition-all duration-200 hover:bg-white/10 hover:text-white"
            title="Download Report"
          >
            <Download size={18} />
          </button>
          <button
            onClick={handleCopy}
            className="bg-primary/10 hover:bg-primary/20 text-primary border-primary/20 flex items-center gap-2 rounded-lg border px-3 py-2 transition-all duration-200"
          >
            {copied ? <Check size={16} /> : <Copy size={16} />}
            <span className="text-xs font-medium">{copied ? 'Copied' : 'Copy'}</span>
          </button>
        </div>
      </div>

      {/* Content */}
      <div className="scrollbar-thin scrollbar-thumb-white/10 scrollbar-track-transparent flex-1 overflow-y-auto bg-gradient-to-b from-transparent to-black/20 p-8">
        <article className="prose prose-invert prose-headings:font-bold prose-headings:tracking-tight prose-h1:text-3xl prose-h1:text-white prose-h2:text-2xl prose-h2:text-white/90 prose-h3:text-xl prose-h3:text-white/80 prose-p:text-gray-300 prose-p:leading-relaxed prose-strong:text-white prose-code:text-primary prose-code:bg-primary/10 prose-code:rounded prose-code:px-1 prose-code:py-0.5 prose-pre:bg-[#0f1014] prose-pre:border prose-pre:border-white/5 prose-li:text-gray-300 prose-blockquote:border-l-primary prose-blockquote:bg-white/5 prose-blockquote:py-1 prose-blockquote:px-4 prose-hr:border-white/10 max-w-none">
          <ReactMarkdown>{content}</ReactMarkdown>
        </article>

        <div className="mt-12 flex items-center justify-center border-t border-white/5 pt-8">
          <p className="text-muted-foreground flex items-center gap-2 text-xs">
            <span className="bg-primary/50 h-1.5 w-1.5 rounded-full" />
            End of Report
            <span className="bg-primary/50 h-1.5 w-1.5 rounded-full" />
          </p>
        </div>
      </div>
    </motion.div>
  );
}
