import ReactMarkdown from 'react-markdown';
import { Copy, Check, Download } from 'lucide-react';
import { useState } from 'react';
import { motion } from 'framer-motion';

interface ReportViewProps {
  content: string;
  source?: string;
}

export function ReportView({ content, source = 'System' }: ReportViewProps) {
  const [copied, setCopied] = useState(false);

  const handleCopy = () => {
    navigator.clipboard.writeText(content);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownload = () => {
    const blob = new Blob([content], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `mission-report-${new Date().toISOString().slice(0, 10)}.md`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <motion.div
      initial={{ opacity: 0, scale: 0.95 }}
      animate={{ opacity: 1, scale: 1 }}
      transition={{ duration: 0.5, ease: 'easeOut' }}
      className="group relative flex h-full flex-col overflow-hidden"
    >
      {/* Header - SIMPLIFIED for Dock Embedding */}
      <div className="flex shrink-0 items-center justify-between border-b border-white/5 px-4 pb-2">
        <div className="text-muted-foreground flex items-center gap-2 text-xs">
          <span className="relative flex h-2 w-2">
            <span className="absolute inline-flex h-full w-full animate-ping rounded-full bg-green-400 opacity-75"></span>
            <span className="relative inline-flex h-2 w-2 rounded-full bg-green-500"></span>
          </span>
          <span>Generated by {source}</span>
        </div>

        <div className="flex items-center gap-1">
          <button
            onClick={handleDownload}
            className="text-muted-foreground rounded-md p-1.5 transition-colors hover:bg-white/10 hover:text-white"
            title="Download"
          >
            <Download size={14} />
          </button>
          <button
            onClick={handleCopy}
            className="text-muted-foreground rounded-md p-1.5 transition-colors hover:bg-white/10 hover:text-white"
            title={copied ? 'Copied' : 'Copy'}
          >
            {copied ? <Check size={14} /> : <Copy size={14} />}
          </button>
        </div>
      </div>

      {/* Content */}
      <div className="scrollbar-thin scrollbar-thumb-white/10 scrollbar-track-transparent flex-1 overflow-y-auto p-6">
        <article className="prose prose-invert prose-headings:font-bold prose-headings:tracking-tight prose-h1:text-2xl prose-h1:text-white prose-h2:text-xl prose-h2:text-white/90 prose-h3:text-lg prose-h3:text-white/80 prose-p:text-gray-300 prose-p:leading-relaxed prose-strong:text-white prose-code:text-primary prose-code:bg-primary/10 prose-code:rounded prose-code:px-1 prose-code:py-0.5 prose-pre:bg-[#0f1014] prose-pre:border prose-pre:border-white/5 prose-li:text-gray-300 prose-blockquote:border-l-primary prose-blockquote:bg-white/5 prose-blockquote:py-1 prose-blockquote:px-4 prose-hr:border-white/10 max-w-none text-sm">
          <ReactMarkdown>{content}</ReactMarkdown>
        </article>

        <div className="mt-12 flex items-center justify-center border-t border-white/5 pt-8">
          <p className="text-muted-foreground flex items-center gap-2 text-xs">
            <span className="bg-primary/50 h-1.5 w-1.5 rounded-full" />
            End of Report
            <span className="bg-primary/50 h-1.5 w-1.5 rounded-full" />
          </p>
        </div>
      </div>
    </motion.div>
  );
}
