"""add metadata to step_logs

Revision ID: 25f601fdc6f7
Revises: af7161f0a6cb
Create Date: 2026-01-08 09:43:12.583479

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '25f601fdc6f7'
down_revision: Union[str, Sequence[str], None] = 'af7161f0a6cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('step_logs', sa.Column('metadata_', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('step_logs', 'metadata_')
    # ### end Alembic commands ###
